name: docs
on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install and Build 🔧
        env:
          TZ: Asia/Shanghai
        run: |
          export GOOGLE_GA=${{ secrets.GOOGLE_GA }} GOOGLE_SEARCH_CONSOLE=${{ secrets.GOOGLE_SEARCH_CONSOLE }}
          git --no-pager log --oneline -n 20
          npm install
          npm run docs:build

      - name: Deploy Github 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/.vuepress/dist
          target_branch: gh-pages
          commit_message: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
